[package]
name = "temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.9" }
regex = { version = "1.5.5" }
tokio = { version = "1.17.0", features = ["full"] }